/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as appTopicsRouteImport } from './routes/(app)/topics'
import { Route as appSettingsRouteImport } from './routes/(app)/settings'
import { Route as appDraftsRouteImport } from './routes/(app)/drafts'
import { Route as appDashboardRouteImport } from './routes/(app)/dashboard'
import { Route as appComposeRouteImport } from './routes/(app)/compose'
import { Route as appAnalyticsRouteImport } from './routes/(app)/analytics'
import { Route as ApiLinkedinCallbackRouteImport } from './routes/api/linkedin/callback'
import { Route as ApiLinkedinAuthorizeRouteImport } from './routes/api/linkedin/authorize'
import { Route as ApiCronTickRouteImport } from './routes/api/cron/tick'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const appTopicsRoute = appTopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsRoute = appSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appRouteRoute,
} as any)
const appDraftsRoute = appDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => appRouteRoute,
} as any)
const appDashboardRoute = appDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appRouteRoute,
} as any)
const appComposeRoute = appComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => appRouteRoute,
} as any)
const appAnalyticsRoute = appAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => appRouteRoute,
} as any)
const ApiLinkedinCallbackRoute = ApiLinkedinCallbackRouteImport.update({
  id: '/api/linkedin/callback',
  path: '/api/linkedin/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinkedinAuthorizeRoute = ApiLinkedinAuthorizeRouteImport.update({
  id: '/api/linkedin/authorize',
  path: '/api/linkedin/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronTickRoute = ApiCronTickRouteImport.update({
  id: '/api/cron/tick',
  path: '/api/cron/tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof appAnalyticsRoute
  '/compose': typeof appComposeRoute
  '/dashboard': typeof appDashboardRoute
  '/drafts': typeof appDraftsRoute
  '/settings': typeof appSettingsRoute
  '/topics': typeof appTopicsRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/cron/tick': typeof ApiCronTickRoute
  '/api/linkedin/authorize': typeof ApiLinkedinAuthorizeRoute
  '/api/linkedin/callback': typeof ApiLinkedinCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof appAnalyticsRoute
  '/compose': typeof appComposeRoute
  '/dashboard': typeof appDashboardRoute
  '/drafts': typeof appDraftsRoute
  '/settings': typeof appSettingsRoute
  '/topics': typeof appTopicsRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/cron/tick': typeof ApiCronTickRoute
  '/api/linkedin/authorize': typeof ApiLinkedinAuthorizeRoute
  '/api/linkedin/callback': typeof ApiLinkedinCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(app)/analytics': typeof appAnalyticsRoute
  '/(app)/compose': typeof appComposeRoute
  '/(app)/dashboard': typeof appDashboardRoute
  '/(app)/drafts': typeof appDraftsRoute
  '/(app)/settings': typeof appSettingsRoute
  '/(app)/topics': typeof appTopicsRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/cron/tick': typeof ApiCronTickRoute
  '/api/linkedin/authorize': typeof ApiLinkedinAuthorizeRoute
  '/api/linkedin/callback': typeof ApiLinkedinCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/compose'
    | '/dashboard'
    | '/drafts'
    | '/settings'
    | '/topics'
    | '/sign-in'
    | '/sign-up'
    | '/api/health'
    | '/auth/callback'
    | '/api/cron/tick'
    | '/api/linkedin/authorize'
    | '/api/linkedin/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/compose'
    | '/dashboard'
    | '/drafts'
    | '/settings'
    | '/topics'
    | '/sign-in'
    | '/sign-up'
    | '/api/health'
    | '/auth/callback'
    | '/api/cron/tick'
    | '/api/linkedin/authorize'
    | '/api/linkedin/callback'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(auth)'
    | '/(app)/analytics'
    | '/(app)/compose'
    | '/(app)/dashboard'
    | '/(app)/drafts'
    | '/(app)/settings'
    | '/(app)/topics'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/api/health'
    | '/auth/callback'
    | '/api/cron/tick'
    | '/api/linkedin/authorize'
    | '/api/linkedin/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiCronTickRoute: typeof ApiCronTickRoute
  ApiLinkedinAuthorizeRoute: typeof ApiLinkedinAuthorizeRoute
  ApiLinkedinCallbackRoute: typeof ApiLinkedinCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/topics': {
      id: '/(app)/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof appTopicsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/drafts': {
      id: '/(app)/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof appDraftsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/compose': {
      id: '/(app)/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof appComposeRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/analytics': {
      id: '/(app)/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof appAnalyticsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/api/linkedin/callback': {
      id: '/api/linkedin/callback'
      path: '/api/linkedin/callback'
      fullPath: '/api/linkedin/callback'
      preLoaderRoute: typeof ApiLinkedinCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/linkedin/authorize': {
      id: '/api/linkedin/authorize'
      path: '/api/linkedin/authorize'
      fullPath: '/api/linkedin/authorize'
      preLoaderRoute: typeof ApiLinkedinAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/tick': {
      id: '/api/cron/tick'
      path: '/api/cron/tick'
      fullPath: '/api/cron/tick'
      preLoaderRoute: typeof ApiCronTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface appRouteRouteChildren {
  appAnalyticsRoute: typeof appAnalyticsRoute
  appComposeRoute: typeof appComposeRoute
  appDashboardRoute: typeof appDashboardRoute
  appDraftsRoute: typeof appDraftsRoute
  appSettingsRoute: typeof appSettingsRoute
  appTopicsRoute: typeof appTopicsRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appAnalyticsRoute: appAnalyticsRoute,
  appComposeRoute: appComposeRoute,
  appDashboardRoute: appDashboardRoute,
  appDraftsRoute: appDraftsRoute,
  appSettingsRoute: appSettingsRoute,
  appTopicsRoute: appTopicsRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiCronTickRoute: ApiCronTickRoute,
  ApiLinkedinAuthorizeRoute: ApiLinkedinAuthorizeRoute,
  ApiLinkedinCallbackRoute: ApiLinkedinCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
